/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() 
    {
        initComponents();
        setNombresComponentes();
        llenarListaProfesor();
        llenarListaEstudiante();
        llenarListaCurso();
    }
    
    private void setNombresComponentes()
    {
        jList1.setName("listaProfesor");
        jList2.setName("listaEstudiante");
        jList3.setName("listaCurso");
        jButton1.setName("agregarProfesor");
        jButton2.setName("agregarEstudiante");
        jButton3.setName("agregarCurso");
    }
    
    public void llenarListaProfesor()
    {
        DefaultListModel dlp = new DefaultListModel();
        dlp = new DefaultListModel();
        ArrayList <Profesor> pr = Profesor.leer();
        
        for (int i=0; i< pr.size(); i++)
        {
            dlp.addElement("Profesor "+ pr.get(i).getNombre()+" - id: "+pr.get(i).getId());
        }
        jList1.setModel(dlp);
    }

    public void llenarListaEstudiante()
    {
        DefaultListModel dle = new DefaultListModel();
        dle = new DefaultListModel();
        ArrayList <Estudiante> est = Estudiante.leer();
        
        for (int i=0; i< est.size(); i++)
        {
            dle.addElement("Estudiante "+ est.get(i).getNombre()+" - id: "+est.get(i).getId());
        }
        jList2.setModel(dle);
    }
    
        public void llenarListaCurso()
    {
        DefaultListModel dlc = new DefaultListModel();
        dlc = new DefaultListModel();
        ArrayList <Curso> cu = Curso.leer();
        
        for (int i=0; i< cu.size(); i++)
        {
            dlc.addElement("Curso "+ cu.get(i).getNombre());
        }
        jList3.setModel(dlc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel1.setText("Colegio UNI");

        jButton1.setText("Agregar Profesor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Estudiante");

        jButton3.setText("Agregar Curso");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(84, 84, 84)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        Profe p = new Profe();
        Profe.jButton1.setVisible(false);

        int fila = jList1.getSelectedIndex();
        if (fila == -1)
        {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario");
        }
        else
        {
            String a = jList1.getSelectedValue();
            int id = Integer.parseInt(a.split(": ")[1]);
            Profesor pr = new Profesor();
            pr.lee(id);
            
            Profe.jLabel1.setText("Profesor Id: " + id);
            Profe.jTextField1.setText(pr.lee(id).getNombre());
            Profe.jTextField2.setText(pr.lee(id).getCorreo());
            Profe.jTextField3.setText(Integer.toString(pr.lee(id).getEdad()));
            
            p.setVisible(rootPaneCheckingEnabled);
        }         
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
        
        Estud e = new Estud();
        Estud.jButton1.setVisible(false);

        int fila = jList2.getSelectedIndex();
        if (fila == -1)
        {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario");
        }
        else
        {
            String a = jList2.getSelectedValue();
            int id = Integer.parseInt(a.split(": ")[1]);
            Estudiante es = new Estudiante();
            es.lee(id);
            
            Estud.jLabel1.setText("Estudiante Id: "+ id);
            Estud.jTextField1.setText(es.lee(id).getNombre());
            Estud.jTextField2.setText(es.lee(id).getCelular());
            Estud.jTextField3.setText(Integer.toString(es.lee(id).getEdad()));
            
            DefaultListModel dlc = new DefaultListModel();
            dlc = new DefaultListModel();            
            ArrayList<Curso> cursos = Curso.extraerCursoEstudiante(id);

            for (int i=0; i< cursos.size(); i++)
            {
                dlc.addElement( cursos.get(i).getNombre());
            }
            Estud.jList1.setModel(dlc);              
            
            e.setVisible(rootPaneCheckingEnabled);
        }         
        
    }//GEN-LAST:event_jList2MouseClicked

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        // TODO add your handling code here:
        Cur c = new Cur();
        Cur.jButton1.setVisible(false);

        int fila = jList3.getSelectedIndex();
        if (fila == -1)
        {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario");
        }
        else
        {
            String nombre = (jList3.getSelectedValue().substring(6));
            Curso cu = new Curso();
            cu.lee(nombre);
            
            Cur.jLabel1.setText("Curso Id: "+cu.lee(nombre).getId());
            Cur.jTextField1.setText(cu.lee(nombre).getNombre());
            Cur.jTextField2.setText(Integer.toString(cu.lee(nombre).getCapacidad()));
            
            Profesor p = new Profesor();
            p.lee(cu.lee(nombre).getIdProfe());
            Cur.jTextField3.setText(p.lee(cu.lee(nombre).getIdProfe()).getNombre());
            
            DefaultListModel dlc = new DefaultListModel();
            dlc = new DefaultListModel();
            ArrayList<Estudiante> est = Estudiante.extraerEstudianteByCurso(cu.lee(nombre).getId());
        
            for (int i=0; i< est.size(); i++)
            {
                dlc.addElement( est.get(i).getNombre());
            }
            Cur.ListaCurso.setModel(dlc);
            
            c.setVisible(rootPaneCheckingEnabled);
        }   
        
    }//GEN-LAST:event_jList3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}